#!/usr/bin/env python
from isotyper.qualitycontrol._qc_settings import (
    FAIL_FILE,
    FILTERED_OUT,
    FILTERED_OUT_NT,
    FILTERING_REPORT,
    PRIMER_FILE,
    PRIMER_TAG_FILE,
    PRIMER_TAG_FILE_COUNT,
    REFJ,
    REFVP,
    REF_CONST,
    SEQ_FASTA_FILE1,
    SEQ_FASTA_FILE2,
    TMP_FILE,
    TRIM1_ALL,
    TRIM2_J,
    TRIM3_RED,
    UNTRIMMED_FASTA,
)

__all__ = [
    "FAIL_FILE",
    "FILTERED_OUT",
    "FILTERED_OUT_NT",
    "FILTERING_REPORT",
    "PRIMER_FILE",
    "PRIMER_TAG_FILE",
    "PRIMER_TAG_FILE_COUNT",
    "REFJ",
    "REFVP",
    "REF_CONST",
    "SEQ_FASTA_FILE1",
    "SEQ_FASTA_FILE2",
    "TMP_FILE",
    "TRIM1_ALL",
    "TRIM2_J",
    "TRIM3_RED",
    "UNTRIMMED_FASTA",
]
