name: isotyper
channels:
- conda-forge
- bioconda
- anaconda
- defaults
dependencies:
- numpy
- pandas
- networkx
- pip
- pytest
- blast
- mafft
- samtools
- picard-slim
- cd-hit
- pip:
  - pytest-cov
