name: vulture

on:
  pull_request:
    branches-ignore:
      - "legacy"
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    name: vulture
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Scavenge
        uses: anaynayak/python-vulture-action@v1.0
        id: vulture
        with:
          vulture-args: example --min-confidence 90